# ----------------- General Settings -----------------
name: Enhancement_RetinexFormer_LOL_v1
model_type: ImageCleanModel
scale: 1
num_gpu: 1
manual_seed: 100

# ----------------- Dataset Settings -----------------
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
    dataroot_gt: lol_dataset/our485/high
    dataroot_lq: lol_dataset/our485/low
    geometric_augs: true
    filename_tmpl: '{}'
    io_backend:
      type: disk
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    mini_batch_sizes: [8]
    iters: [300000]
    gt_size: 128
    gt_sizes: [128]
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: lol_dataset/eval15/high
    dataroot_lq: lol_dataset/eval15/low
    io_backend:
      type: disk

# ----------------- Network Settings -----------------
network_g:
  type: RetinexFormer
  in_channels: 3
  out_channels: 3
  n_feat: 40
  stage: 1
  num_blocks: [1,2,2]

# ----------------- Path Settings -----------------
path:
  pretrain_network_g: D:/Major/PSR/retinexformer-env/Retinexformer/experiments/RetinexFormer_LOL_v1/models/net_g_latest.pth
  strict_load_g: true
  resume_state: ~
  experiments_root: experiments/RetinexFormer_LOL_v1

# ----------------- Training Settings -----------------
train:
  total_iter: 20000
  warmup_iter: -1
  use_grad_clip: true

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [10000, 10000]
    restart_weights: [1,1]
    eta_mins: [0.00001, 0.000001]

  mixing_augs:
    mixup: true
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: Adam
    lr: 0.0002        # safe float
    betas: [0.9, 0.999]

  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# ----------------- Validation Settings -----------------
val:
  window_size: 4
  val_freq: 500        # safe integer
  save_img: true
  rgb2bgr: true
  use_image: true
  max_minibatch: 1

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# ----------------- Logging Settings -----------------
logger:
  print_freq: 500
  save_checkpoint_freq: 1000
  use_tb_logger: true
  tb_logger:
    log_dir: experiments/RetinexFormer_LOL_v1/tb_logger
  wandb:
    project: low_light
    resume_id: ~

# ----------------- Distributed Settings -----------------
dist_params:
  backend: nccl
  port: 29500
